workflows:
  android-app:
    name: Android App
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      java: 11
    scripts:
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Create complete Gradle Wrapper
        script: |
          echo "Removing existing Gradle wrapper files"
          rm -f ./gradlew
          rm -rf ./gradle
          
          echo "Creating new Gradle wrapper"
          mkdir -p gradle/wrapper
          
          echo "Downloading Gradle Wrapper JAR"
          curl -L -o gradle/wrapper/gradle-wrapper.jar https://raw.githubusercontent.com/gradle/gradle/v7.0.2/gradle/wrapper/gradle-wrapper.jar
          
          echo "Creating gradle-wrapper.properties"
          cat > gradle/wrapper/gradle-wrapper.properties << EOF
          distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-bin.zip
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dists
          EOF
          
          echo "Creating gradlew script"
          curl -L -o gradlew https://raw.githubusercontent.com/gradle/gradle/v7.0.2/gradlew
          
          echo "Making gradlew executable"
          chmod +x ./gradlew
          
          echo "Listing files"
          ls -la
          ls -la gradle/wrapper/
      - name: Check Project Structure
        script: |
          echo "=== Project Root ==="
          ls -la
          
          echo "=== App Directory ==="
          ls -la app/
          
          echo "=== Src Directory ==="
          ls -la app/src/
          
          echo "=== Main Directory ==="
          ls -la app/src/main/
          
          echo "=== Java Directory ==="
          ls -la app/src/main/java/
          
          echo "=== Build Gradle ==="
          cat build.gradle
          
          echo "=== App Build Gradle ==="
          cat app/build.gradle
          
          echo "=== Settings Gradle ==="
          cat settings.gradle
          
          echo "=== AndroidManifest.xml ==="
          cat app/src/main/AndroidManifest.xml
      - name: Fix app structure if needed
        script: |
          # Ensure required directories exist
          mkdir -p app/src/main/java/com/example/videotimetracker
          mkdir -p app/src/main/res/layout
          mkdir -p app/src/main/res/values
          
          # Check if manifest exists, create if not
          if [ ! -f app/src/main/AndroidManifest.xml ]; then
            echo "Creating minimal AndroidManifest.xml"
            cat > app/src/main/AndroidManifest.xml << EOF
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="com.example.videotimetracker">
              <uses-permission android:name="android.permission.PACKAGE_USAGE_STATS" />
              <application
                  android:allowBackup="true"
                  android:label="VideoTimeTracker"
                  android:supportsRtl="true">
                  <activity android:name=".MainActivity" android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF
          fi
      - name: Build debug APK
        script: |
          echo "Attempting build with logging"
          # Try to build with a clean first
          ./gradlew clean
          ./gradlew assembleDebug --stacktrace --info || true
          
          # Show build reports
          echo "===== BUILD REPORTS ====="
          find app/build/reports -name "*.html" -exec cat {} \;
    artifacts:
      - app/build/outputs/apk/debug/*.apk 