workflows:
  android-app:
    name: Android App
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      java: 11
    scripts:
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Create complete Gradle Wrapper
        script: |
          echo "Removing existing Gradle wrapper files"
          rm -f ./gradlew
          rm -rf ./gradle
          
          echo "Creating new Gradle wrapper"
          mkdir -p gradle/wrapper
          
          echo "Downloading Gradle Wrapper JAR"
          curl -L -o gradle/wrapper/gradle-wrapper.jar https://raw.githubusercontent.com/gradle/gradle/v7.0.2/gradle/wrapper/gradle-wrapper.jar
          
          echo "Creating gradle-wrapper.properties"
          cat > gradle/wrapper/gradle-wrapper.properties << EOF
          distributionBase=GRADLE_USER_HOME
          distributionPath=wrapper/dists
          distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-bin.zip
          zipStoreBase=GRADLE_USER_HOME
          zipStorePath=wrapper/dists
          EOF
          
          echo "Creating gradlew script"
          curl -L -o gradlew https://raw.githubusercontent.com/gradle/gradle/v7.0.2/gradlew
          
          echo "Making gradlew executable"
          chmod +x ./gradlew
          
          echo "Listing files"
          ls -la
          ls -la gradle/wrapper/
      - name: Check Project Structure
        script: |
          echo "=== Project Root ==="
          ls -la
          
          echo "=== App Directory ==="
          ls -la app/
          
          echo "=== Build Gradle ==="
          cat build.gradle
          
          echo "=== App Build Gradle ==="
          cat app/build.gradle
          
          echo "=== Settings Gradle ==="
          cat settings.gradle
      - name: Build debug APK
        script: |
          echo "Attempting build with full verbosity"
          ./gradlew assembleDebug --stacktrace --info --debug --scan
    artifacts:
      - app/build/outputs/apk/debug/*.apk 